test

diff --git a/.github/workflows/publish-docs.yml b/.github/workflows/publish-docs.yml
--- a/.github/workflows/publish-docs.yml
+++ b/.github/workflows/publish-docs.yml
@@ -13,40 +13,40 @@ jobs:
       fail-fast: false
 
     steps:
-      - uses: actions/checkout@v2
-      - uses: r-lib/actions/setup-pandoc@v1
+    - uses: docker://pandoc/core:2.9
+    - uses: actions/checkout@v2
 
-      - uses: ammaraskar/sphinx-action@master
-        with:
-          pre-build-command: python -m pip install -r requirements.txt -r requirements-dev.txt
-          build-command: "make html"
-          docs-folder: "docs/"
+    - uses: ammaraskar/sphinx-action@master
+      with:
+        docs-folder: "docs/"
+        pre-build-command: python -m pip install -r requirements.txt -r requirements-dev.txt
+        build-command: "make html"
 
-      # Create an artifact of the html output.
-      - uses: actions/upload-artifact@v1
-        with:
-          name: DocumentationHTML
-          path: docs/_build/html/
+    # Create an artifact of the html output.
+    - uses: actions/upload-artifact@v2
+      with:
+        name: DocumentationHTML
+        path: docs/_build/html/
 
-      # Publish built docs to gh-pages branch.
-      - name: Commit documentation changes
-        # Only once from master or a tag
-        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
-        run: |
-          git clone https://github.com/bambinos/formulae.git --branch gh-pages --single-branch gh-pages
-          cp -r docs/_build/html/* gh-pages/
-          cd gh-pages
-          touch .nojekyll
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add .
-          git commit -m "Update documentation" -a || true
-          # The above command will fail if no changes were present, so we ignore that.
+    # Publish built docs to gh-pages branch.
+    - name: Commit documentation changes
+    # Only once from master or a tag
+      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
+      run: |
+        git clone https://github.com/bambinos/formulae.git --branch gh-pages --single-branch gh-pages
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        touch .nojekyll
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore that.
 
-      - name: Push changes
-        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
-        uses: ad-m/github-push-action@master
-        with:
-          branch: gh-pages
-          directory: gh-pages
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+    - name: Push changes
+      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
